enum codes {
    NOT_FOUND = 1,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    MISSING_SCOPE,
    BOT_OFFLINE,
    INVALID_BODY,
    DUPLICATE,
    INVALID_INVITE,
    MISSING_GUILD,
    MISSING_CHARACTER,
    MISSING_ATTRIBUTE,
    MISSING_EVENT,
}

export default codes;
